app:
  app-name: changcheng-ops
  allow-generate-api: true
  allow-cross-domain-access: true
  order-path: /tmp/
  template-order-path: report/template/report_userOrder_templet.xls
  after-sale-remind-days: 7
  customer-services-mobile: 18336070691
  
logging:
  config: classpath:log.xml
server:
  port: 23000
  session-timeout: 1800
spring:
  mvc:
    favicon:
      enabled: false
  http:
    encoding:
      charset: utf-8
  datasource:
    name: datasource
    initialize: false
    #jdbc:mysql://ilovemldu.mysql.rds.aliyuncs.com:3506/maserati_app_dev?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://123.56.24.21:3306/cc_interface?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
    #url: jdbc:mysql://localhost:3306/mydemodatabase?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 920512
    driverClassName: com.mysql.jdbc.Driver
    